### ISSUE TITLE
Bug js edit page with Goomento/PageBuilder on Magento 2.4.5

### ISSUE THREAD

**Issue by davidduong90** [Goomento/PageBuilder#18]
When I install the extension Goomento/PageBuilder on Magento 2.4.5 and I try to edit content of a page, it shows a bug like this
https://prnt.sc/VDf5JdFgHK4c

Please share with me how to fix it. Thanks

**Comment by haihv433** [comment]
Hi @davidduong90 

Can you inspect the element and see this selector on DOM, it should be the same as here view-source:https://goomento.com/goomento-the-free-magento-page-builder-extension

![image](https://user-images.githubusercontent.com/32940422/194311412-aa26970f-3365-47e4-8072-9b6a7885d324.png)

If not, I think there were something in your theme, which prevent the Goomento to fully functional 

Also, pls check on log files at `var/log/exception.log` and `var/log/pagebuilder/error.log` these might reveal thing

**Comment by davidduong90** [comment]
Hello @haihv433,

Thank you for getting back to me. But This is just Magento 2.4.5 with sample data, I don't install any extensions or theme. You can log in here:
https://magegeek.com/magento245/admin
user: haihv433
password: haihv433@Goomento

Best regards,

David

**Comment by haihv433** [comment]
Hi @davidduong90 

I checked your site and can not figure out for sure, but you can try this 

at `registration.php` file (for Goomento_Core and Goomento_PageBuilder extensions), change the line of 

```
isset($file) ? dirname($file) : __DIR__
``` 
to 
```
__DIR__
```
I made this in case of multiple instances can use one source, but seems to be the bug here,

Pls let me know if this work, 

If not,can you send to me the logs file? `var/debug.log` and `var/pagebuilder/error.log` (Pls remove all the sensitive data)

**Comment by davidduong90** [comment]
Hello @haihv433 ,

It works. Thank you so much for your great support!

Best regards,

David

**Comment by haihv433** [comment]
Thank @davidduong90 

I will fix this and the patch will be available in next version, 

I close this issue for now
