### ISSUE TITLE
Cross origin issue

### ISSUE THREAD

**Issue by Lelinh698** [Goomento/PageBuilder#39]
Hi, my magento store using multiple website so that when i edit a page, cross origin issue happened.
How can I solve this problem?
Many thanks.

Console errors:
`Refused to display 'http://mystore.local/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`
`Uncaught DOMException: Failed to read a named property 'goomentoFrontend' from 'Window': Blocked a frame with origin "http://magento.local" from accessing a cross-origin frame.`

**Comment by haihv433** [comment]
Hi @Lelinh698 

`X-Frame-Options` was set by your web server such as Nginx or Apache (or from Magento),and blocked by browser, in order to work on multiple domains  which are sharing the same resource, you need to config it by your self, (and not related to this extension) 

You can check this document https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/security/xframe-options.html 

Hope this help
